mejoras

diff --git a/install-sh b/install-sh
--- a/install-sh
+++ b/install-sh
@@ -7,29 +7,29 @@ msg () {
         es)
         case "$1" in
             option) printf "Seleccione la versión o \033[1mC\033[0m para cancelar: " ;;
-            0) printf "\033[1m¡Instalado correctamente!\033[0m\n" ;;
-            1) printf 'Instalación cancelada.\n' ;;
-            2) printf 'Uso incorrecto. %s\n' "$correct" ;;
-            3) printf 'Opción incorrecta. %s\n' "$correct" ;;
-            4) printf 'Ejecute \033[7mrehash\033[0m o reinicie la terminal.\n' ;;
-            5) printf 'Error durante la copia del archivo.\n' ;;
+            0) printf "\033[1m¡Instalado correctamente!\033[0m" ;;
+            1) printf 'Instalación cancelada.' ;;
+            2) printf 'Uso incorrecto. %s' "$correct" ;;
+            3) printf 'Opción incorrecta. %s' "$correct" ;;
+            4) printf 'Ejecute \033[7mrehash\033[0m o reinicie la terminal.' ;;
+            5) printf 'Error durante la copia del archivo.' ;;
         esac ;;
         *)
         case "$1" in
             option) printf "Choose a version or \033[1mC\033[0m to cancel: " ;;
-            0) printf "\033[1mSuccessfully installed!\033[0m\n" ;;
-            1) printf 'Installation cancelled.\n' ;;
-            2) printf 'Invalid usage. %s\n' "$correct" ;;
-            3) printf 'Incorrect option. %s\n' "$correct" ;;
-            4) printf 'Run \033[7mrehash\033[0m or restart the terminal.\n' ;;
-            5) printf 'Error copying file.\n' ;;
+            0) printf "\033[1mSuccessfully installed!\033[0m" ;;
+            1) printf 'Installation cancelled.' ;;
+            2) printf 'Invalid usage. %s' "$correct" ;;
+            3) printf 'Incorrect option. %s' "$correct" ;;
+            4) printf 'Run \033[7mrehash\033[0m or restart the terminal.' ;;
+            5) printf 'Error copying file.' ;;
         esac ;;
     esac
-    case "$1" in
-        option|0|1) [ -n "$2" ] && exit $1 ;;
-        4) exit 0 ;;
-        *) exit $1 ;;
-    esac
+    if [ "$1" = option ]; then
+        return 0
+    else
+        return $1
+    fi
 }
 
 o=''
@@ -41,23 +41,24 @@ case "$#" in
         printf '\033[1m1\033[0m.- Python\n'
         printf '\033[1m2\033[0m.- Shell (POSIX)\n'
         msg option
-        IFS= read -r o || msg 1 aux
+        IFS= read -r o || o="$(msg 1)"
         case "$o" in
             1) OPTION='--python' ;;
             2) OPTION='--sh-posix' ;;
-            C|c) msg 1; exit 0 ;;
+            C|c) OPTION=C; o="$(msg 1)"; printf "%s\n" "$o" ;;
             *) o='' ;;
         esac
     done
 ;;
     1) ;;
-    *) msg 2 ;;
+    *) OPTION=C; o="$(msg 2)"; printf "%s\n" "$o" ;;
 esac
 
 case "$OPTION" in
     -py|--python) file='apt_trixie.py' ;;
     -sh|--sh-posix) file='apt_trixie.sh' ;;
-    *) msg 3 ;;
+    C|c) ;;
+    *) o="$(msg 3)"; printf "%s\n" "$o" ;;
 esac
 
 if [ "$(id -u)" -gt 0 ]; then
@@ -66,16 +67,22 @@ if [ "$(id -u)" -gt 0 ]; then
 fi
 to='/usr/local/bin/apt'
 
-if [ "$(id -u)" -eq 0 ]; then
-    cp "$file" "$to" && chmod +x "$to"
-    ret="$?"
-else
-    sudo sh -c "cp '$file' '$to' && chmod +x '$to'"
-    ret="$?"
-fi
-if [ "$ret" -eq 0 ]; then
-    msg 0
-    hash -r
-else
-    msg 5
+if [ ! -n "$o" ]; then
+    if [ "$(id -u)" -eq 0 ]; then
+        cp "$file" "$to" && chmod +x "$to"
+        ret="$?"
+    else
+        sudo sh -c "cp '$file' '$to' && chmod +x '$to'"
+        ret="$?"
+    fi
+    if [ "$ret" -eq 0 ]; then
+        o="$(msg 0)"; printf "%s\n" "$o"
+        hash -r
+        if [ "${SHELL##*/}" = 'zsh' ]; then
+            o="$(msg 4)"
+            printf "%s\n" "$o"
+        fi
+    else
+        o="$(msg 5)"; printf "%s\n" "$o"
+    fi
 fi
